export const title = {
  'sign-in': 'WELCOME TO PRO FITNESS!',
  'sign-up': 'CREATE ACCOUNTS',
  'forgot-password': 'FORGOT PASSWORD',
  splash: 'PRO FITNESS',
  splash2: 'PERFECT BODY DOING CROSSFIT EXERCISES',
  splash3: 'SHOT STRONG TIMELESS MAN TRAINING',
  splash4: 'PERFECT BODY DOING CROSSFIT EXERCISES',
  verify: 'VERIFY ACCOUNT',
  splash0: 'We train your body to be great and fit.',
  banner: 'FIT YOUNG MAN DOING BATTLE STRETCH TRAINING',
  'meal-plan': 'MEAL PLANS',
  'full-exercise': 'FULL EXERCISE',
  delete: 'Delete!',
  'save-exercise': 'SAVE EXERCISE TO...',
  result: 'RESULT',
  'meal-plan-1': 'Meal Plan',
  notification: 'NOTIFICATIONS',
  sleep: 'SLEEP',
  setting: 'SETTING',
  profile: 'PROFILE',
  'edit-profile': 'EDIT PROFILE',
  'full-name': 'Full Name',
  categories: 'CATEGORIES',
  dashboard: 'DASHBOARD',
  'my-progress': 'MY PROGRESS',
  'new-workout': 'NEW WORKOUT',
  playlist: 'PLAYLIST',
  estimate: 'ESTIMATE',
  
};

export const button = {
  'sign-in': 'LOGIN',
  'reset-password': 'RESET PASSWORD',
  'sign-up': 'CREATE ACCOUNT',
  resend: 'Resend',
  'next-step': 'NEXT STEPS',
  'get-started': 'GET STARTED!',
  'finish-step': 'FINISH STEPS',
  start: `LET'S START`,
  skip: 'SKIP',
  next: 'NEXT',
  'start-exercise': 'Start Exercise',
  'start-now': 'START NOW',
  'create-plan': 'CREATE NEW PLAYLIST',
  done: 'DONE',
  start: 'START',
  save: 'SAVE',
  eat: 'EAT',
  create: 'CREATE WORKOUT',
  'start-now': 'START NOW',
};

export const text = {
  'forgot-password': 'Forgot password?',
  'sub-sign-in': `Hello there, sign in to continue!`,
  'sub-forgot-password':
    'Please enter your email below to reveive your password reset code.',
  'sub-sign-up': 'Please enter your credentials to proceed',
  'sub-verify': 'Verify your account by entering verification code we sent to',
  'sub-start':
    'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.',
  'sub-start-2':
    'Sculpt your ideal body, free your true self, transform your life.',
  workout: 'Workout',
  'workout-2': 'Workout summary',
  'total-time': 'Total Time',
  'total-calories': 'Total Calories',
  level: 'Level',
  category: 'Category',
  weight: 'Weight',
  'total-weight': 'Total Weight',
  kcal: 'kcal',
  fat: 'Fat',
  protein: 'Protein',
  carbs: 'Carbs',
  others: 'Others',
  reminder: 'Reminder',
  'change-password': 'Change Password',
  height: 'Height',
  age: 'Age',
  'grams-per-day': 'Grams per day',
  practice: 'Practice',
  sleep: 'Sleep',
  calories: 'Calories',
};

export const placeholder = {
  email: 'Enter email...',
  password: 'Enter password...',
  name: 'Enter name...',
  phone: 'Enter phone...',
  address: 'Enter address...',
  new_password: 'Enter new password...',
  confirm_password: 'Enter confirm password...',
  age: 'Enter age...',
  weight: 'Enter weight...',
  height: 'Enter height...',
  workout: 'Enter Workout name ...',
};

export const titleForm = {
  email: 'Email address',
  password: 'Password',
  address: 'Address',
  name: 'Full Name',
  phone: 'Phone',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  level: 'Fitness Level',
  goal: 'Fitness Goal',
  weight: 'Weight (kg)',
  height: 'Height (cm)',
  gender: 'Gender',
  age: 'Age',
};

export const step = {
  'step-2': 'Step 2 of 8',
  'step-3': 'Step 3 of 8',
  'step-4': 'Step 4 of 8',
  'step-5': 'Step 5 of 8',
  'step-6': 'Step 6 of 8',
  'step-7': 'Step 7 of 8',
  'step-8': 'Step 8 of 8',
  'title-2': 'HOW OLD ARE YOU?',
  'title-3': 'WHAT IS YOUR GENDER?',
  'title-4': 'HOW MUCH DO YOU WEIGHT?',
  'title-5': `WHAT'S YOUR GOAL WEIGHT?`,
  'title-6': 'HOW MUCH DO YOU HEIGHT?',
  'title-7': `WHAT'S YOUR FITNESS LEVEL?`,
  'title-8': `WHAT'S YOUR GOAL?`,
  'title-start': "LET'S GET STARTED",
};

export const titleHome = {
  'title-1': 'SELECT YOUR GOAL',
  'title-2': 'CATEGORY',
  'title-3': 'POPULAR EXERCISES',
  'title-4': 'MEAL PLANS',
  'title-5': 'ADDITIONAL EXERCISES',
};

export const navigator = {
  main: 'Main',
  'detail-exercise': 'DetailExercise',
  category: 'Category',
  'full-exercise': 'FullExercise',
  'detail-meal': 'DetailMeal',
  'progress-exercise': 'ProgressExercise',
  result: 'Result',
  'meal-plan': 'MealPlan',
  notification: 'Notification',
  dashboard: 'Dashboard',
  playlist: 'Playlist',
  setting: 'Setting',
  profile: 'Profile',
  sleep: 'Sleep',
  progress: 'Progress',
  'change-password': 'ChangePassword',
  'create-plan': 'CreatePlan',
  'exercises-in-list': 'ExercisesInList',
  splash: 'Splash',
  introduction: 'Introduction',
  'sign-in': 'SignIn',
  'sign-up': 'Register',
  'forgot-password': 'ForgotPassword',
  verify: 'Verify',
  'change-password': 'ChangePassword',
  'profile-user': 'ProfileUser',
  'edit-profile': 'EditProfile',
  home: 'Home',
  meal: 'Meal',
  camera: 'Camera',
  exercise: 'Exercise',
  finish: 'Finish',
  profile: 'Profile',
  'sign-up-2': 'SignUp',
  gender: 'Gender',
  goal: 'Goal',
  height: 'Height',
  weight: 'Weight',
  old: 'Old',
  level: 'Level',
  start: 'Start',
  'goal-weight': 'GoalWeight',
};

export const message = {
  required: 'This field cannot empty',
  'invalid-email': 'Not a valid email',
  'invalid-password': 'Password must be at least 8 characters',
  delete: 'Are you sure you want to delete?',
};
