const SALT_ROUNDS = 10;
const FAIL = 100;
const SUCCESS = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const ACCEPTED = 202;
const NO_CONTENT = 204;
const MOVED_PERMANENTLY = 301;
const FOUND = 302;
const NOT_MODIFIED = 304;
const TEMPORARY_REDIRECT = 307;
const PERMANENT_REDIRECT = 308;
const TOO_MANY_REQUESTS = 429;
const SERVICE_UNAVAILABLE = 503;
const GATEWAY_TIMEOUT = 504;
const UNPROCESSABLE_ENTITY = 422;

module.exports = {
    SALT_ROUNDS,
    SUCCESS,
    CREATED,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    ACCEPTED,
    NO_CONTENT,
    MOVED_PERMANENTLY,
    FOUND,
    NOT_MODIFIED,
    TEMPORARY_REDIRECT,
    PERMANENT_REDIRECT,
    TOO_MANY_REQUESTS,
    SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT,
    UNPROCESSABLE_ENTITY,
    FAIL
};