const VALIDATION = 0
const SIGN_UP = 1;
const SIGN_IN = 2;
const VERIFY_ACCOUNT = 3;
const LOGOUT = 4;
const DECODE_TOKEN = 5;
const SEND_OTP = 6;
const VERIFY_OTP = 7;
const FORGOT_PASSWORD = 8;
const VIEW_PROFILE = 9;
const RENEW_TOKEN = 10;
const UPDATE_PROFILE = 11;
const GET_CATEGORY = 12;
const GET_EXERCISE = 13;
const GET_DETAIL_EXERCISE = 14;
const GET_DASHBOARD = 15;
const UPDATE_DASHBOARD = 16;
const GET_RESULT_EXERCISE = 17;
module.exports = {
    VALIDATION,
    SIGN_UP,
    SIGN_IN,
    VERIFY_ACCOUNT,
    LOGOUT,
    DECODE_TOKEN,
    SEND_OTP,
    VERIFY_OTP,
    FORGOT_PASSWORD,
    VIEW_PROFILE,
    RENEW_TOKEN,
    UPDATE_PROFILE,
    GET_CATEGORY,
    GET_EXERCISE,
    GET_DETAIL_EXERCISE,
    GET_DASHBOARD,
    UPDATE_DASHBOARD,
    GET_RESULT_EXERCISE
};